### ISSUE TITLE
Modifying ORBSLAM2

### ISSUE THREAD

**Issue by danbo2** [jskinn/ORB_SLAM2-PythonBindings#11]
Hi,

I don't understand the 'Modifying ORBSLAM2' part. When I use 'make install', I meet the error 'No rule to make target 'install''. Can you me some hints?

Thanks

**Comment by jskinn** [comment]
The base implementation of ORBSLAM2 doesn't include many methods for extracting data, only for saving it to file. To make the bindings work and read data out from it, we need to add some extra methods. The other thing we need the base ORBSLAM2 to do that it does not by default is to build a library file with `make install`.
All the required changes are summarised in [orbslam_changes.diff](https://github.com/jskinn/ORB_SLAM2-PythonBindings/blob/master/orbslam-changes.diff).
You can apply it to your cloned ORBSLAM2 implemenation using `git apply orbslam_changes.diff` from inside the ORBSLAM2 folder.
This is what puts the install target in the ORBSLAM cmake folder.

**Comment by danbo2** [comment]
@jskinn Can you give me a more specific instruction ? I am not a CS student. Do I need to copy orbslam_changes.diff to some location ? Do I need to add some instructions in CMakeLists.txt ?

**Comment by danbo2** [comment]
Hi@jskinn , I meet an issue when modify ORB_SLAM source using git apply .diff. I put them in the same folder, but the result is in the below.
![diff](https://user-images.githubusercontent.com/16380245/68978923-1e380f00-07ca-11ea-88a1-838891149f82.PNG)
