### ISSUE TITLE
make error: has no member named ‘GetTracker’, has no member named ‘GetKeyFrames’

### ISSUE THREAD

**Issue by linpeisensh** [jskinn/ORB_SLAM2-PythonBindings#20]
@jskinn 
When I run make, this error occurs, could you help me out?
![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png)
Thank you for your excellent work!

**Comment by QingquanBao** [comment]
> @jskinn When I run make, this error occurs, could you help me out? ![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png) Thank you for your excellent work!

@linpeisensh  Hi, could you recall how you dealt with this problem? Thank you for any help!!!!

**Comment by SunwoongPaik** [comment]
> > @jskinn When I run make, this error occurs, could you help me out? ![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png) Thank you for your excellent work!
> 
> @linpeisensh Hi, could you recall how you dealt with this problem? Thank you for any help!!!!

did U get any answers from him??

can U plz share to me?
Thank you

**Comment by QingquanBao** [comment]
> > > @jskinn When I run make, this error occurs, could you help me out? ![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png) Thank you for your excellent work!
> > 
> > 
> > @linpeisensh Hi, could you recall how you dealt with this problem? Thank you for any help!!!!
> 
> did U get any answers from him??
> 
> can U plz share to me? Thank you

Sorry, it has been a long time and I forget a bit.

I think the problem is that you have not applied `orbslam-changes.diff`.  After that, it should be good.

**Comment by SunwoongPaik** [comment]
> 

I solved just few minutes ago. haha

Yeah U were write proper patching orbslam-changes.diff was the key

Thanks anyway
best regards,

**Comment by SunwoongPaik** [comment]
> > > > @jskinn When I run make, this error occurs, could you help me out? ![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png) Thank you for your excellent work!
> > > 
> > > 
> > > @linpeisensh Hi, could you recall how you dealt with this problem? Thank you for any help!!!!
> > 
> > 
> > did U get any answers from him??
> > can U plz share to me? Thank you
> 
> Sorry, it has been a long time and I forget a bit.
> 
> I think the problem is that you have not applied `orbslam-changes.diff`. After that, it should be good.

orbslam-changes.diff

**Comment by SunwoongPaik** [comment]
> > > > @jskinn When I run make, this error occurs, could you help me out? ![image](https://user-images.githubusercontent.com/52672986/101995294-45148d80-3cc9-11eb-8b35-2fb664c2986b.png) Thank you for your excellent work!
> > > 
> > > 
> > > @linpeisensh Hi, could you recall how you dealt with this problem? Thank you for any help!!!!
> > 
> > 
> > did U get any answers from him??
> > can U plz share to me? Thank you
> 
> Sorry, it has been a long time and I forget a bit.
> 
> I think the problem is that you have not applied `orbslam-changes.diff`. After that, it should be good.

I just solved this problem.

U were write .orbslam-changes.diff was the key.
Thanks anyway,
Best regards,
